Repository Swe574-Group4/Swe574-Group4, pull requests merged in 2021-12, with the labels that each got.

#53 Improvements made for Advanced Search
  medicles/services.py
  medicles/templates/medicles/advanced_search.html
  medicles/views.py
Labels: priority/important-soon

#56 Following user implemented
  .gitignore
  actions/__init__.py
  actions/admin.py
  actions/apps.py
  actions/migrations/0001_initial.py
  actions/migrations/__init__.py
  actions/models.py
  actions/tests.py
  actions/utils.py
  actions/views.py
  medicles/admin.py
  medicles/apps.py
  medicles/migrations/0008_contact.py
  medicles/models.py
  medicles/templates/medicles/user_search_results.html
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
  pubmed_project/urls.py
Labels: priority/critical-urgent

#59 User activity feature added
  docker-compose.yml
  medicles/migrations/0007_auto_20211128_1347.py
  medicles/migrations/0009_search.py
  medicles/migrations/0010_auto_20211213_1335.py
  medicles/migrations/0011_auto_20211213_1419.py
  medicles/models.py
  medicles/templates/medicles/index.html
  medicles/templates/medicles/user_activity.html
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
Labels: enhancement, priority/critical-urgent

#73 Linked favourite article feature with activity steam
  actions/utils.py
  medicles/migrations/0009_favouritelisttable.py
  medicles/models.py
  medicles/templates/medicles/detail.html
  medicles/templates/medicles/favourites.html
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
Labels: enhancement
