Repository Swe574-Group4/Swe574-Group4, pull requests merged in 2021-11, with the labels that each got.

#31 Local deployment comments added
  pubmed_project/settings.py
Labels: bug, field/database, field/devops

#37 Search function updated
  .dockerignore
  Dockerfile
  docker-compose.yml
  medicles/__init__.py
  medicles/apps.py
  medicles/models.py
  medicles/static/medicles/css/bootstrap-grid.css
  medicles/static/medicles/css/bootstrap-grid.css.map
  medicles/static/medicles/css/bootstrap-grid.min.css
  medicles/static/medicles/css/bootstrap-grid.min.css.map
  medicles/static/medicles/css/bootstrap-grid.rtl.css
  medicles/static/medicles/css/bootstrap-grid.rtl.css.map
  medicles/static/medicles/css/bootstrap-grid.rtl.min.css
  medicles/static/medicles/css/bootstrap-grid.rtl.min.css.map
  medicles/static/medicles/css/bootstrap-reboot.css
  medicles/static/medicles/css/bootstrap-reboot.css.map
  medicles/static/medicles/css/bootstrap-reboot.min.css
  medicles/static/medicles/css/bootstrap-reboot.min.css.map
  medicles/static/medicles/css/bootstrap-reboot.rtl.css
  medicles/static/medicles/css/bootstrap-reboot.rtl.css.map
  medicles/static/medicles/css/bootstrap-reboot.rtl.min.css
  medicles/static/medicles/css/bootstrap-reboot.rtl.min.css.map
  medicles/static/medicles/css/bootstrap-utilities.css
  medicles/static/medicles/css/bootstrap-utilities.css.map
  medicles/static/medicles/css/bootstrap-utilities.min.css
  medicles/static/medicles/css/bootstrap-utilities.min.css.map
  medicles/static/medicles/css/bootstrap-utilities.rtl.css
  medicles/static/medicles/css/bootstrap-utilities.rtl.css.map
  medicles/static/medicles/css/bootstrap-utilities.rtl.min.css
  medicles/static/medicles/css/bootstrap-utilities.rtl.min.css.map
  medicles/static/medicles/css/bootstrap.css
  medicles/static/medicles/css/bootstrap.css.map
  medicles/static/medicles/css/bootstrap.min.css
  medicles/static/medicles/css/bootstrap.min.css.map
  medicles/static/medicles/css/bootstrap.rtl.css
  medicles/static/medicles/css/bootstrap.rtl.css.map
  medicles/static/medicles/css/bootstrap.rtl.min.css
  medicles/static/medicles/css/bootstrap.rtl.min.css.map
  medicles/templates/medicles/index.html
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
  pubmed_project/urls.py
  requirements.txt
Labels: enhancement, priority/critical-urgent

#39 Advanced search implemented. Title, author list, date, and keywords search will be possible.
  .gitignore
  medicles/migrations/0007_auto_20211128_1347.py
  medicles/models.py
  medicles/static/medicles/css/mystyle.css
  medicles/templates/medicles/advanced_search.html
  medicles/templates/medicles/index.html
  medicles/templates/medicles/search_results.html
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
  requirements.txt
Labels: priority/important-soon
