Repository Swe574-Group4/Swe574-Group4, pull requests merged in 2022-01, with the labels that each got.

#74 search user with tag implemented
  medicles/templates/medicles/profile.html
  medicles/templates/medicles/user_search_results.html
  medicles/views.py
Labels: enhancement

#76 Redirection bug fixed
  actions/migrations/0004_auto_20211220_1626.py
  medicles/migrations/0009_search.py
  medicles/templates/medicles/user_search_results.html
  medicles/views.py
Labels: bug, priority/critical-urgent

#77 User's favorite articles page added
  medicles/templates/medicles/favourites.html
  medicles/urls.py
  medicles/views.py
Labels: enhancement

#79 Pagination enhancement added
  medicles/templates/medicles/search_results.html
  medicles/views.py
Labels: enhancement

#80 User activity improvements have been made
  medicles/static/medicles/css/mystyle.css
  medicles/templates/medicles/index.html
  medicles/views.py
  pubmed_project/settings.py
  pubmed_project/urls.py
  requirements.txt
Labels: enhancement, priority/important-soon, field/ui

#81 Advanced Search updated
  medicles/migrations/0013_annotation_article_id.py
  medicles/models.py
  medicles/templates/medicles/advanced_search.html
  medicles/templates/medicles/advanced_searchresults.html
  medicles/templates/medicles/detail.html
  medicles/templates/medicles/index.html
  medicles/tests.py
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
Labels: enhancement

#88 CSS file storage account links added
  medicles/templates/medicles/index.html
  medicles/templates/medicles/profile.html
  medicles/templates/medicles/user_search.html
  pubmed_project/settings.py
Labels: bug, priority/critical-urgent

#89 Anonymous user exception added
  medicles/views.py
Labels: bug

#82 annotation feature front-end implementation is completed
  .DS_Store
  actions/models.py
  actions/utils.py
  annotations/__init__.py
  annotations/apps.py
  annotations/migrations/0001_initial.py
  annotations/migrations/0002_annotationmodel_article_id.py
  annotations/migrations/0003_remove_annotationmodel_article_id.py
  annotations/migrations/__init__.py
  annotations/models.py
  annotations/tests.py
  annotations/utils.py
  manage.py
  medicles/templates/medicles/detail.html
  medicles/tests.py
  medicles/urls.py
  medicles/views.py
  pubmed_project/settings.py
Labels: enhancement

#91 Overall improvements and bug fixes
  actions/models.py
  actions/utils.py
  aks-deploy.yaml
  azure-pipelines.yml
  init.sh
  medicles/delete.py
  medicles/forms.py
  medicles/models.py
  medicles/services.py
  medicles/templates/medicles/user_search_results.html
  medicles/templatetags/__init__.py
  medicles/templatetags/action_tags.py
  medicles/tests.py
  medicles/views.py
  pubmed_project/settings.py
  ssh_setup.sh
  sshd_config
Labels: bug, priority/critical-urgent

#93 Advanced search fixed after tests.
  .DS_Store
  .gitignore
  medicles/.DS_Store
  medicles/templates/medicles/advanced_search.html
  medicles/templates/medicles/advanced_searchresults.html
  medicles/tests.py
  medicles/views.py
Labels: bug, enhancement

#97 Feature/profile favourites
  medicles/models.py
  medicles/templates/medicles/profile.html
  medicles/views.py
Labels: enhancement

#99 Multi-word search enabled
  medicles/templates/medicles/advanced_searchresults.html
  medicles/views.py
Labels: enhancement

#100 Annotation activity and user following bugs added
  actions/migrations/0005_auto_20220106_1215.py
  actions/models.py
  medicles/migrations/0014_customuser.py
  medicles/migrations/0015_auto_20220106_1425.py
  medicles/models.py
  medicles/views.py
Labels: bug, enhancement

#104 dismiss button feature fixed
  medicles/templates/medicles/detail.html
Labels: bug

#105 Bug fixes and unit tests
  medicles/tests.py
  medicles/views.py
Labels: bug

#106 Clicking bugs on follow actions
  medicles/templates/medicles/profile.html
  medicles/templates/medicles/user_search_results.html
Labels: bug, priority/critical-urgent

#108 Code explanation added and links corrected for advanced search.
  medicles/templates/medicles/advanced_search.html
  medicles/templates/medicles/advanced_searchresults.html
  medicles/templates/medicles/detail.html
  medicles/templates/medicles/profile.html
  medicles/templates/medicles/user_search.html
  medicles/templates/medicles/user_search_results.html
  medicles/tests.py
  medicles/views.py
Labels: enhancement

#111 Search optimizations
  medicles/templates/medicles/detail.html
  medicles/views.py
Labels: bug
